### ISSUE TITLE
error: ‘calcMotionGradient’ is not a member of ‘cv’

### ISSUE THREAD

**Issue by LuciaXu** [libhand/libhand#12]
build libhand on ubuntu 14.04.
follow the instruction in Building LibHand on Debian/Ubuntu (and derivatives).
However, during the make process, get error like this:

In member function ‘void libhand::ImageToHogCalculator::CalcHog(const cv::Mat&, const cv::Mat&, libhand::HogDescriptor*)’:
error: ‘calcMotionGradient’ is not a member of ‘cv’
   cv::calcMotionGradient(gray_image_, // input grayscale iamge
   ^
make[2]: *** [hand_cpp/source/CMakeFiles/hand_hog.dir/image_to_hog_calculator.cc.o] Error 1
make[1]: *** [hand_cpp/source/CMakeFiles/hand_hog.dir/all] Error 2
make: *** [all] Error 2

is this because of the wrong version of opencv? the version I get through "apt-get install" is 2.4.8

**Comment by shasheene** [comment]
Yes, the problem is because you appear to also have OpenCV 3 installed. libhand still uses OpenCV 2.4 (as this is he only version available in the Ubuntu 14.04 repositories).

However, looking at the public forks, it appears trivial to manually adapt the required changes for successful compilation, available [here](https://github.com/GlueCrow/libhand/commit/e0c90b4b9e6af4c49c2f7ff8efaeea5a2d916b16) so if you want you can do that.

For completeness, I note I created a new blank instance of Ubuntu 14.04 in a container and manually ran the steps listed [here](https://github.com/libhand/libhand/blob/master/docs/build_instructions/debian/BUILD.DEBIAN.md) via copy & paste. I confirmed that libhand builds without issue as libopencv-dev is '2.4.8+dfsg1-2ubuntu1'. That suggests you have somehow also installed OpenCV 3.0 on your system (which CMake is finding).

By the way, in future for readability, please wrap error messages in code blocks with two backticks (`)

**Comment by LuciaXu** [comment]
Thanks very much for your help. The problem is solved.
