### ISSUE TITLE
libhand-windows

### ISSUE THREAD

**Issue by scvman** [libhand/libhand#3]
Hi,all

I want to ask if LIBHAND could be compiled and used in windows if using OGRE and BOOST win32 libraries. Do anyone successfully finished it? Thanks.

scvman

**Comment by shasheene** [comment]
Hi scvman,

There is a fork of this libhand repository that was done [by Mega28](https://github.com/Mega28/libhand/commits/master). It appears to have made the required changes for compilation on Windows.

It's probably easiest to simply clone that repository and work from there (alternatively, cherry-picking those commits onto this branch and resolve the conflicts manually).

I'm currently actively maintaining a fork LibHand on a private repository (and pushing perfected changes to my public LibHand fork on GitHub, and merging the changes here). Easy compilation on Windows (as well as integrating of [AppVeyer](https://www.appveyor.com/) Windows Continuous Integration) is certainly my intention longer term, but I have a long list of improvements to make to LibHand (both to the v0.9 API, which is the latest official release by Libhand's initial author Marin Saric, and more radical API-breaking changes that may become the defacto LibHand v1.0), so I don't know when I'll get around to adding Windows compilation support.

I don't know how much CMake experience you have, but I'd expect with Windows you will likely need to populate the paths to OGRE and BOOST libraries in the CMakeCache.txt file via the CMake GUI (on Debian/Ubuntu, OGRE places the *.cmake files in a common search path to tell CMake where to find OGRE - I don;t believe it's automatic on Windows but I may be wrong).

Just a word of warning - LibHand has historically been difficult to compile and cleanly use as a library (which is why I'm slowly improving and documenting it all). There's a lot of required dependencies (which in my mind are unnecessary and should be removed) like tcl/tk GUI toolkit that you will probably need to install (and potentially specify CMake paths to).

Good luck - I'm sorry that I haven't yet got around to adding Windows support, writing clear/concise build instructions or integration a Windows continuous integration build bot yet. It may even be a few months until it becomes my number one maintenance priority for LibHand.

**Comment by scvman** [comment]
Hi, shasheene

Thank you for your detailed instructions. I have successfully re-build the window-fork from Mega28. Great work Mega28 done! I downloaded OGRE 1.9.0 SDK from http://sourceforge.net/projects/ogre/files/ogre/1.9/1.9/OgreSDK_vc11_v1-9-0.exe/download
and used boost 1.6.1. Also activetcl was used for 'wish' command. The hand model was right shown in the window. Thanks again.

**Comment by shasheene** [comment]
No problem! Glad to have helped you get set up!

This weekend, I'll cherry-pick those commits and open a new pull request myself (along with adding some detailed documentation to the README.md)

@jonkeane, I suggest this issue be reopened and left open because this branch does not yet support Windows compilation yet. I expect I will be pushing a steady stream of libhand v0.9 improvements in the next couple weeks/months to this repository. I'll try and be as efficient as possible with your time, and purely focus only on libhand v0.9 maintenance type stuff, leaving my larger, complex API-breaking improvements (like being able to much more easily and cleanly use libhand as a library) on my public GitHub fork.
