### ISSUE TITLE
hand skin color texture and background

### ISSUE THREAD

**Issue by rahul-islam** [libhand/libhand#8]
I have two question --

1.  How to change color texture of skin of rendered hand models ?
2.  How to change or add custom background to rendered hand shape?

**Comment by shasheene** [comment]
> How to change or add custom background to rendered hand shape?

You would have to look through the OGRE 3D documentation and modify the C++ code to add a scene around the rendered hand. It's not something I've tried to do with LibHand yet, so I'm not sure how.

> How to change color texture of skin of rendered hand models ?

The texture is located at `hand_model/blender/hand_texture.png`:

![hand_texture](https://cloud.githubusercontent.com/assets/1414379/22728980/85c372d8-ee30-11e6-9883-322aa7ad4d86.png)

The reason the texture is warped is due to UV mapping. Modifying this file allows would allow you to change the skin color of the hand in any way you like. It it's certainly should be enough to apply a simple skin color change. It's possible to do something like this: (youtube video)

[![How to Change a Person's Skin Color from Dark to Light in Photoshop](https://img.youtube.com/vi/pO7gq_2BvZw/0.jpg)](https://www.youtube.com/watch?v=pO7gq_2BvZw).

I'm sure you can find some tutorials on the web for Gimp or your preferred image manipulation tool. 

For more complex changes that require changes to specific parts of the hand, the UV mapping makes it almost impossible. To modify in 3D, you need to use a program like Blender to paint the texture in 3D. (Warning: Blender has a large learning curve if you don't have 3D modelling experience). Here's a tutorial I have used in the past when I needed to modify the LibHand model: (youtube video)

[![Unwrapping and Texturing in Blender 3d (Clone Painting)](https://img.youtube.com/vi/p4ngVoGIj1Q/0.jpg)](https://www.youtube.com/watch?v=p4ngVoGIj1Q)

If you produce a high quality modified skin color version, I'd be happy to include it as part of LibHand. LibHand should certainly be bundled with a comprehensive set of hand textures (as well has hand poses) to save everyone recreating them.

(If anyone is interested, a VERY far in the future enhancement to LibHand will allow texturing the hand using a photograph of your OWN hand, which is functionality is required for my project [gloveTrack](https://github.com/shasheene/gloveTrack). However, at the current rate, it will probably be years until a pull request is ready unfortunately).

**Comment by shasheene** [comment]
I'm closing this issue now.

As mentioned above:
> If you produce a high quality modified skin color version, I'd be happy to include it as part of LibHand. LibHand should certainly be bundled with a comprehensive set of hand textures (as well has hand poses) to save everyone recreating them.

There probably would be some value in packaging up my comment above as a README.md for the hand model, but it's such a low priority that it's probably not worth it.

Feel free to comment here if you produce a hand texture. Even if it's not perfect it still might be useful for other people!
